name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-test:
    name: Build and Test with Swift ${{ matrix.swift }} on ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        swift: ["6.2"]
    runs-on: ${{ matrix.os }}

    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Up Swift ${{ matrix.swift }}
        uses: swift-actions/setup-swift@v2
        with:
          swift-version: ${{ matrix.swift }}

      - name: Swift Version
        run: swift --version

      - name: Resolve Dependencies
        run: swift package resolve

      - name: Build
        run: swift build

      - name: Test
        run: swift test
